name: Docker Image CI
 
on:
  push:
    branches: [ main ]
 
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
 
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: 125122558@qq.com
        password: txg63106
 
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: singlor/github:1.0
        build: .
